# Generated by Django 3.0.5 on 2020-04-23 22:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_resposibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="comp",
            field=models.TextField(blank=True, null=True),
        ),
    ]
