# Generated by Django 3.0.5 on 2020-04-24 14:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_auto_20200423_2249"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="technos",
            field=models.ManyToManyField(related_name="project", to="cv.Techno"),
        ),
    ]
