default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SECRET_KEY: ""
  SENTRY_DSN: ""

development:
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - .yyyakovlev.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: false

test:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"

travis:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"