default:
  ALLOWED_HOSTS: []
  DATABASE_URL: ""
  DEBUG: true
  SENTRY_DSN: ""
  RECAPTCHA_SITE_KEY: ""
  RECAPTCHA_SECRET_KEY: ""
  BOT_TOKEN: ""
  TELEGA_ADMIN: ""

development:
  DEBUG: true

heroku:
  ALLOWED_HOSTS:
    - yyyakovlev.herokuapp.com
    - 127.0.0.1
    - localhost
  DEBUG: false

test:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"

travis:
  MODE_CACHING: true
  MODE_DEBUG: true
  MODE_PROFILING: false
  SECRET_KEY: "1"